### ISSUE TITLE
Broken footer social icon links - itch.io and Github

### ISSUE THREAD

**Issue by livviest** [solarpunksc/solarpunksc.github.io#22]
The footer icons for itch.io and Github currently only append their respective `href` contents to the base URL (`https://thefuture.wtf/`) when clicked (e.g. clicking the Github icon takes the user to `https://thefuture.wtf/github.com/solarpunksc`, which yields 404).

To fix, prepend `https://www.` to the itch.io and Github icon `href` attributes.

**Comment by ChrisRenfrow** [comment]
If contributions are welcome, I would be happy to fork and submit a PR with the necessary changes.

**Comment by nikAleksandr** [comment]
Thanks. Happy to make this quick fix! Not against collaboration, though.
